In [320]:
import pandas as pd

In [321]:
df=pd.read_csv("Copy of Titanic_train.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [322]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [323]:
print(df.shape)

(891, 12)

In [324]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [325]:
print(df.dtypes)

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [326]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [327]:
df.isnull().sum().idxmax()

'Cabin'

In [328]:
print("numerical columns\n",df.select_dtypes(include='number'))
len(df.select_dtypes(include="object").columns)

numerical columns
      PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare
0              1         0       3  22.0      1      0   7.2500
1              2         1       1  38.0      1      0  71.2833
2              3         1       3  26.0      0      0   7.9250
3              4         1       1  35.0      1      0  53.1000
4              5         0       3  35.0      0      0   8.0500
..           ...       ...     ...   ...    ...    ...      ...
886          887         0       2  27.0      0      0  13.0000
887          888         1       1  19.0      0      0  30.0000
888          889         0       3   NaN      1      2  23.4500
889          890         1       1  26.0      0      0  30.0000
890          891         0       3  32.0      0      0   7.7500

[891 rows x 7 columns]

C:\Users\Risha\AppData\Local\Temp\ipykernel_3064\3299987602.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  len(df.select_dtypes(include="object").columns)

5

In [329]:
df[(df["Sex"]=="male") & (df["Pclass"]==3)].shape[0]

347

In [330]:
df[df["Pclass"]==1]["Age"].mean()

np.float64(38.233440860215055)

In [331]:
df.loc[df["Fare"].idxmin()]

PassengerId                    180
Survived                         0
Pclass                           3
Name           Leonard, Mr. Lionel
Sex                           male
Age                           36.0
SibSp                            0
Parch                            0
Ticket                        LINE
Fare                           0.0
Cabin                          NaN
Embarked                         S
Name: 179, dtype: object

In [332]:
df[(df["Sex"]=="female") & df["Survived"]==1].shape[0]

233

In [333]:
df[df["Sex"] == "female"]["Fare"].mean()

np.float64(44.47981783439491)

In [334]:
df.duplicated().sum()

np.int64(0)

In [335]:
print("no. of passengers who survived:")
print((df["Survived"]==1).sum())

print("no. of passengers who didnt survive:",(df["Survived"]==0).sum())

no. of passengers who survived:
342
no. of passengers who didnt survive: 549

In [336]:
#percentage of missing values
m=((df.isnull().sum())/len(df))*100
print("percentage of missing values:\n",m)

percentage of missing values:
 PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64

In [337]:
df["Sex"].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [338]:
df["Pclass"].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [339]:
print(df["Age"].mean())

29.69911764705882

In [340]:
print((df["Age"]>60).sum())

22

In [341]:
print(df["Fare"].min())
print(df["Fare"].max())

0.0
512.3292

In [342]:
df_clean=df.copy()
df_clean.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [343]:
#Handling missing values
df_clean["Age"]=df_clean["Age"].fillna(df_clean["Age"].median())
df_clean["Embarked"]=df_clean["Embarked"].fillna(df_clean["Embarked"].mode()[0])
df_clean =df_clean.drop(["Cabin","PassengerId","Name","Ticket"], axis=1)

# we are dropping name and ticket column because they dont give us any useful information about weather the person survived or not

In [344]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
df_clean["Sex"]=le.fit_transform(df["Sex"])

In [345]:
from sklearn.preprocessing import OneHotEncoder

on=OneHotEncoder()
encoded=on.fit_transform(df[["Embarked"]])

encoded_df=pd.DataFrame(
    encoded.toarray(),
    columns= on.get_feature_names_out(["Embarked"]),
    index=df_clean.index
)

df_clean= df_clean.drop("Embarked", axis=1)
df_clean = pd.concat([df_clean, encoded_df], axis=1)

In [346]:
df_clean.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S,Embarked_nan
0,0,3,1,22.0,1,0,7.2500,0.0,0.0,1.0,0.0
1,1,1,0,38.0,1,0,71.2833,1.0,0.0,0.0,0.0
2,1,3,0,26.0,0,0,7.9250,0.0,0.0,1.0,0.0
3,1,1,0,35.0,1,0,53.1000,0.0,0.0,1.0,0.0
4,0,3,1,35.0,0,0,8.0500,0.0,0.0,1.0,0.0

In [350]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
scaled= scaler.fit_transform(df_clean[["Age","Fare"]])
df_clean[["Age","Fare"]]=scaled

In [351]:
df_clean[["Age","Fare"]].head()

        Age      Fare
0 -0.565736 -0.502445
1  0.663861  0.786845
2 -0.258337 -0.488854
3  0.433312  0.420730
4  0.433312 -0.486337

In [352]:
print(df_clean["Age"].mean())
print(df_clean["Fare"].mean())

-2.791133080988048e-17
3.987332972840069e-18

In [353]:
x=df_clean.drop("Survived", axis=1)
y=df_clean["Survived"]

In [356]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x, y, test_size=0.2, random_state=42)

In [357]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(712, 10)
(179, 10)
(712,)
(179,)